"use client";
import { useCallback,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { PurchasingTabs } from "@/components/purchasing-tabs";
import { Button } from "@/components/ui/button";import { Card,CardHeader } from "@/components/ui/card";import { TextField,SelectField } from "@/components/ui/field";import { EmptyState } from "@/components/ui/empty-state";
import { convertRFQ,createRFQ,listRFQs,listSuppliers,updateRFQStatus } from "@/lib/api/purchasing";import type { PurchaseRFQ,Supplier } from "@/lib/types";import { usePermission } from "@/lib/permissions";import { useToast } from "@/components/ui/toast";
type Line={description:string;quantity:string;unit:string;quoted_unit_cost:string};const blank=():Line=>({description:"",quantity:"1",unit:"slab",quoted_unit_cost:""});
export default function RFQs(){const t=useTranslations("purchasing"),toast=useToast(),router=useRouter(),canWrite=usePermission("purchasing:rfqs:write");const [items,setItems]=useState<PurchaseRFQ[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[supplierId,setSupplierId]=useState(""),[due,setDue]=useState(""),[lines,setLines]=useState<Line[]>([blank()]),[busy,setBusy]=useState(false);const load=useCallback(()=>listRFQs().then(setItems).catch(e=>toast.error(e.message)),[toast]);useEffect(()=>{load();listSuppliers({limit:100}).then(r=>setSuppliers(r.items))},[load]);
async function create(e:React.FormEvent){e.preventDefault();setBusy(true);try{await createRFQ({supplier_id:supplierId,response_due_date:due||undefined,lines:lines.map(x=>({...x,quoted_unit_cost:x.quoted_unit_cost||undefined}))});setLines([blank()]);setSupplierId("");await load();toast.success(t("rfqCreated"))}catch(e){toast.error(e instanceof Error?e.message:t("createFailed"))}finally{setBusy(false)}}
async function status(x:PurchaseRFQ,next:string){try{const total=x.lines.reduce((s,l)=>s+Number(l.quantity)*Number(l.quoted_unit_cost??0),0);await updateRFQStatus(x.id,next,total?String(total):x.quoted_total??undefined);await load()}catch(e){toast.error(e instanceof Error?e.message:t("updateFailed"))}}
return <div className="flex flex-col gap-4"><PurchasingTabs/><div><h1 className="text-xl font-semibold">{t("rfqsTitle")}</h1><p className="text-sm text-text-secondary">{t("rfqsSubtitle")}</p></div>{canWrite&&<Card><CardHeader title={t("createRfq")}/><form onSubmit={create} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><SelectField label={t("supplier")} value={supplierId} onChange={e=>setSupplierId(e.target.value)} required><option value="">—</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</SelectField><TextField type="date" label={t("responseDueDate")} value={due} onChange={e=>setDue(e.target.value)}/></div>{lines.map((l,i)=><div key={i} className="grid gap-2 rounded border border-border p-3 sm:grid-cols-4"><TextField label={t("description")} value={l.description} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,description:e.target.value}:x))} required/><TextField type="number" label={t("quantity")} value={l.quantity} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,quantity:e.target.value}:x))}/><TextField label={t("unit")} value={l.unit} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,unit:e.target.value}:x))}/><TextField type="number" label={t("quotedUnitCost")} value={l.quoted_unit_cost} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,quoted_unit_cost:e.target.value}:x))}/></div>)}<div className="flex gap-2"><Button type="button" variant="secondary" onClick={()=>setLines([...lines,blank()])}>{t("addLine")}</Button><Button type="submit" loading={busy} disabled={!supplierId||lines.some(x=>!x.description)}>{t("createRfq")}</Button></div></form></Card>}{items.length===0?<EmptyState title={t("noRfqs")} description={t("noRfqsDesc")}/>:<div className="overflow-x-auto rounded border border-border"><table className="w-full text-sm"><thead><tr><th className="p-3 text-left">{t("rfqNumber")}</th><th>{t("tableStatus")}</th><th>{t("responseDueDate")}</th><th>{t("tableTotal")}</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-t border-border"><td className="p-3 font-mono">{x.rfq_number}</td><td className="text-center">{t(x.status)}</td><td className="text-center">{x.response_due_date??"—"}</td><td className="text-center">{x.quoted_total??"—"}</td><td className="p-2 text-right">{canWrite&&x.status==="draft"&&<Button variant="secondary" onClick={()=>status(x,"sent")}>{t("send")}</Button>} {canWrite&&x.status==="sent"&&<Button variant="secondary" onClick={()=>status(x,"quoted")}>{t("recordQuote")}</Button>} {canWrite&&x.status==="quoted"&&<Button onClick={async()=>{const po=await convertRFQ(x.id);router.push(`/purchasing/orders/${po.id}`)}}>{t("convertToOrder")}</Button>}</td></tr>)}</tbody></table></div>}</div>}
