"""Domain events published by the Purchasing module."""

SUPPLIER_CREATED = "SupplierCreated"
SUPPLIER_UPDATED = "SupplierUpdated"
PURCHASE_ORDER_CREATED = "PurchaseOrderCreated"
PURCHASE_ORDER_STATUS_CHANGED = "PurchaseOrderStatusChanged"
PURCHASE_ORDER_LINE_RECEIVED = "PurchaseOrderLineReceived"
SUPPLIER_CONTACT_CREATED = "SupplierContactCreated"
RFQ_CREATED = "PurchaseRequestForQuotationCreated"
RFQ_STATUS_CHANGED = "PurchaseRequestForQuotationStatusChanged"
PURCHASE_ORDER_APPROVED = "PurchaseOrderApproved"
PURCHASE_ORDER_REJECTED = "PurchaseOrderRejected"
PURCHASE_RETURN_CREATED = "PurchaseReturnCreated"
PURCHASE_RETURN_COMPLETED = "PurchaseReturnCompleted"
SUPPLIER_PAYMENT_STATUS_CHANGED = "SupplierPaymentStatusChanged"
