"""Tests for Task notifications: assignment/reassignment (created
synchronously as a use-case side effect) and reminder/overdue (generated by
the pull-based check endpoint -- see task_notification_use_cases.py)."""


def test_assigning_task_to_other_user_creates_notification(app_client, owner_headers, rep_user, company):
    from core.auth.models import ROLE_REP
    from core.auth.security import create_access_token

    app_client.post(
        "/api/v1/crm/tasks", headers=owner_headers, json={"title": "For the rep", "assigned_to": str(rep_user.id)}
    )

    rep_token = create_access_token(user_id=rep_user.id, active_company_id=company.id, role=ROLE_REP)
    rep_headers = {"Authorization": f"Bearer {rep_token}"}

    resp = app_client.get("/api/v1/crm/task-notifications", headers=rep_headers)
    assert resp.status_code == 200
    items = resp.json()["items"]
    assert len(items) == 1
    assert items[0]["notification_type"] == "task_assigned"
    assert items[0]["read_at"] is None


def test_assigning_task_to_self_creates_no_notification(app_client, owner_headers, owner_user):
    app_client.post(
        "/api/v1/crm/tasks", headers=owner_headers, json={"title": "For myself", "assigned_to": str(owner_user.id)}
    )
    resp = app_client.get("/api/v1/crm/task-notifications", headers=owner_headers)
    assert resp.json()["items"] == []


def test_reassigning_task_notifies_new_assignee(app_client, owner_headers, rep_user, company):
    from core.auth.models import ROLE_REP
    from core.auth.security import create_access_token

    task = app_client.post("/api/v1/crm/tasks", headers=owner_headers, json={"title": "Reassign me"}).json()
    app_client.patch(
        f"/api/v1/crm/tasks/{task['id']}", headers=owner_headers, json={"assigned_to": str(rep_user.id)}
    )

    rep_token = create_access_token(user_id=rep_user.id, active_company_id=company.id, role=ROLE_REP)
    rep_headers = {"Authorization": f"Bearer {rep_token}"}

    items = app_client.get("/api/v1/crm/task-notifications", headers=rep_headers).json()["items"]
    assert len(items) == 1
    assert items[0]["notification_type"] == "task_reassigned"


def test_check_reminders_generates_reminder_notification(app_client, owner_headers, owner_user):
    task = app_client.post(
        "/api/v1/crm/tasks",
        headers=owner_headers,
        json={
            "title": "Past reminder",
            "assigned_to": str(owner_user.id),
            "due_date": "2030-01-01T00:00:00Z",
            "remind_at": "2020-01-01T00:00:00Z",
        },
    ).json()

    resp = app_client.post("/api/v1/crm/task-notifications/check", headers=owner_headers)
    assert resp.status_code == 200
    created = resp.json()["items"]
    assert len(created) == 1
    assert created[0]["notification_type"] == "task_reminder"
    assert created[0]["task_id"] == task["id"]

    # Idempotent: calling check again must not create a duplicate.
    resp2 = app_client.post("/api/v1/crm/task-notifications/check", headers=owner_headers)
    assert resp2.json()["items"] == []


def test_check_reminders_generates_overdue_notification(app_client, owner_headers, owner_user):
    task = app_client.post(
        "/api/v1/crm/tasks",
        headers=owner_headers,
        json={"title": "Way overdue", "assigned_to": str(owner_user.id), "due_date": "2020-01-01T00:00:00Z"},
    ).json()

    resp = app_client.post("/api/v1/crm/task-notifications/check", headers=owner_headers)
    created = resp.json()["items"]
    assert len(created) == 1
    assert created[0]["notification_type"] == "task_overdue"
    assert created[0]["task_id"] == task["id"]

    resp2 = app_client.post("/api/v1/crm/task-notifications/check", headers=owner_headers)
    assert resp2.json()["items"] == []


def test_check_reminders_ignores_terminal_tasks(app_client, owner_headers, owner_user):
    task = app_client.post(
        "/api/v1/crm/tasks",
        headers=owner_headers,
        json={"title": "Done and overdue", "assigned_to": str(owner_user.id), "due_date": "2020-01-01T00:00:00Z"},
    ).json()
    app_client.post(f"/api/v1/crm/tasks/{task['id']}/status", headers=owner_headers, json={"status": "done"})

    resp = app_client.post("/api/v1/crm/task-notifications/check", headers=owner_headers)
    assert resp.json()["items"] == []


def test_mark_notification_read(app_client, owner_headers, owner_user):
    app_client.post(
        "/api/v1/crm/tasks",
        headers=owner_headers,
        json={"title": "Read me", "assigned_to": str(owner_user.id), "due_date": "2020-01-01T00:00:00Z"},
    )
    created = app_client.post("/api/v1/crm/task-notifications/check", headers=owner_headers).json()["items"]
    notification_id = created[0]["id"]

    resp = app_client.post(f"/api/v1/crm/task-notifications/{notification_id}/read", headers=owner_headers)
    assert resp.status_code == 200
    assert resp.json()["read_at"] is not None

    unread = app_client.get(
        "/api/v1/crm/task-notifications", headers=owner_headers, params={"unread_only": True}
    ).json()["items"]
    assert notification_id not in [n["id"] for n in unread]
