"""Pure value objects for the Orders module."""

ORDER_STATUS_WAITING = "waiting"
ORDER_STATUS_MEASURING = "measuring"
ORDER_STATUS_APPROVED_FOR_PRODUCTION = "approved_for_production"
ORDER_STATUS_IN_PRODUCTION = "in_production"
ORDER_STATUS_READY = "ready"
ORDER_STATUS_DELIVERED = "delivered"
ORDER_STATUS_INSTALLED = "installed"
ORDER_STATUS_COMPLETED = "completed"
ORDER_STATUS_CANCELLED = "cancelled"

VALID_ORDER_STATUSES = {
    ORDER_STATUS_WAITING,
    ORDER_STATUS_MEASURING,
    ORDER_STATUS_APPROVED_FOR_PRODUCTION,
    ORDER_STATUS_IN_PRODUCTION,
    ORDER_STATUS_READY,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_INSTALLED,
    ORDER_STATUS_COMPLETED,
    ORDER_STATUS_CANCELLED,
}

TERMINAL_ORDER_STATUSES = {ORDER_STATUS_COMPLETED, ORDER_STATUS_CANCELLED}

_VALID_ORDER_TRANSITIONS = {
    ORDER_STATUS_WAITING: {ORDER_STATUS_MEASURING, ORDER_STATUS_APPROVED_FOR_PRODUCTION, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_MEASURING: {ORDER_STATUS_APPROVED_FOR_PRODUCTION, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_APPROVED_FOR_PRODUCTION: {ORDER_STATUS_IN_PRODUCTION, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_IN_PRODUCTION: {ORDER_STATUS_READY, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_READY: {ORDER_STATUS_DELIVERED, ORDER_STATUS_INSTALLED, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_DELIVERED: {ORDER_STATUS_INSTALLED, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_INSTALLED: {ORDER_STATUS_COMPLETED, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_COMPLETED: set(),
    ORDER_STATUS_CANCELLED: set(),
}


def is_valid_order_transition(*, current: str, target: str) -> bool:
    if current == target:
        return True
    return target in _VALID_ORDER_TRANSITIONS.get(current, set())
