"""Domain events published by the AI Sales Assistant module."""

LEAD_ANALYZED = "LeadAnalyzed"
CONVERSATION_ANALYZED = "ConversationAnalyzed"
QUOTE_ANALYZED = "QuoteAnalyzed"
TASKS_SUGGESTED = "TasksSuggested"
RECOMMENDATION_ACCEPTED = "RecommendationAccepted"
RECOMMENDATION_REJECTED = "RecommendationRejected"
RECOMMENDATION_EDITED = "RecommendationEdited"
CONVERSATION_REPLY_DRAFTED = "ConversationReplyDrafted"
QUOTE_LINE_ITEMS_DRAFTED = "QuoteLineItemsDrafted"
