"""stone catalog module

Revision ID: 04ccadfeecf3
Revises: 8c35bb34b2fc
Create Date: 2026-06-30 15:47:36.959480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '04ccadfeecf3'
down_revision: Union[str, None] = '8c35bb34b2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_price_lists',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_price_lists_company_id'), 'catalog_price_lists', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_price_lists_status'), 'catalog_price_lists', ['status'], unique=False)
    op.create_table('catalog_warehouses',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_warehouses_company_id'), 'catalog_warehouses', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_warehouses_status'), 'catalog_warehouses', ['status'], unique=False)
    op.create_table('catalog_brands',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_document_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['logo_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_brands_company_id'), 'catalog_brands', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_brands_status'), 'catalog_brands', ['status'], unique=False)
    op.create_table('catalog_collections',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('brand_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog_brands.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_collections_brand_id'), 'catalog_collections', ['brand_id'], unique=False)
    op.create_index(op.f('ix_catalog_collections_company_id'), 'catalog_collections', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_collections_status'), 'catalog_collections', ['status'], unique=False)
    op.create_table('catalog_materials',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('brand_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('collection_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('finish', sa.String(), nullable=True),
    sa.Column('thickness_mm', sa.String(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog_brands.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['catalog_collections.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_materials_brand_id'), 'catalog_materials', ['brand_id'], unique=False)
    op.create_index(op.f('ix_catalog_materials_collection_id'), 'catalog_materials', ['collection_id'], unique=False)
    op.create_index(op.f('ix_catalog_materials_company_id'), 'catalog_materials', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_materials_status'), 'catalog_materials', ['status'], unique=False)
    op.create_table('catalog_material_documents',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('material_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('document_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['catalog_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_material_documents_company_id'), 'catalog_material_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_material_documents_document_id'), 'catalog_material_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_catalog_material_documents_material_id'), 'catalog_material_documents', ['material_id'], unique=False)
    op.create_table('catalog_material_images',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('material_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('document_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['catalog_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_material_images_company_id'), 'catalog_material_images', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_material_images_document_id'), 'catalog_material_images', ['document_id'], unique=False)
    op.create_index(op.f('ix_catalog_material_images_material_id'), 'catalog_material_images', ['material_id'], unique=False)
    op.create_table('catalog_price_list_entries',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('price_list_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('material_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['catalog_materials.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['catalog_price_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_list_id', 'material_id', name='uq_catalog_price_entry_per_material')
    )
    op.create_index(op.f('ix_catalog_price_list_entries_company_id'), 'catalog_price_list_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_price_list_entries_material_id'), 'catalog_price_list_entries', ['material_id'], unique=False)
    op.create_index(op.f('ix_catalog_price_list_entries_price_list_id'), 'catalog_price_list_entries', ['price_list_id'], unique=False)
    op.create_table('catalog_slabs',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('material_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('warehouse_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('slab_number', sa.String(), nullable=False),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('rack_location', sa.String(), nullable=True),
    sa.Column('length_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['catalog_materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['catalog_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'slab_number', name='uq_catalog_slab_number_per_company')
    )
    op.create_index(op.f('ix_catalog_slabs_barcode'), 'catalog_slabs', ['barcode'], unique=False)
    op.create_index(op.f('ix_catalog_slabs_company_id'), 'catalog_slabs', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_slabs_lot_number'), 'catalog_slabs', ['lot_number'], unique=False)
    op.create_index(op.f('ix_catalog_slabs_material_id'), 'catalog_slabs', ['material_id'], unique=False)
    op.create_index(op.f('ix_catalog_slabs_slab_number'), 'catalog_slabs', ['slab_number'], unique=False)
    op.create_index(op.f('ix_catalog_slabs_status'), 'catalog_slabs', ['status'], unique=False)
    op.create_index(op.f('ix_catalog_slabs_warehouse_id'), 'catalog_slabs', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_slabs_warehouse_id'), table_name='catalog_slabs')
    op.drop_index(op.f('ix_catalog_slabs_status'), table_name='catalog_slabs')
    op.drop_index(op.f('ix_catalog_slabs_slab_number'), table_name='catalog_slabs')
    op.drop_index(op.f('ix_catalog_slabs_material_id'), table_name='catalog_slabs')
    op.drop_index(op.f('ix_catalog_slabs_lot_number'), table_name='catalog_slabs')
    op.drop_index(op.f('ix_catalog_slabs_company_id'), table_name='catalog_slabs')
    op.drop_index(op.f('ix_catalog_slabs_barcode'), table_name='catalog_slabs')
    op.drop_table('catalog_slabs')
    op.drop_index(op.f('ix_catalog_price_list_entries_price_list_id'), table_name='catalog_price_list_entries')
    op.drop_index(op.f('ix_catalog_price_list_entries_material_id'), table_name='catalog_price_list_entries')
    op.drop_index(op.f('ix_catalog_price_list_entries_company_id'), table_name='catalog_price_list_entries')
    op.drop_table('catalog_price_list_entries')
    op.drop_index(op.f('ix_catalog_material_images_material_id'), table_name='catalog_material_images')
    op.drop_index(op.f('ix_catalog_material_images_document_id'), table_name='catalog_material_images')
    op.drop_index(op.f('ix_catalog_material_images_company_id'), table_name='catalog_material_images')
    op.drop_table('catalog_material_images')
    op.drop_index(op.f('ix_catalog_material_documents_material_id'), table_name='catalog_material_documents')
    op.drop_index(op.f('ix_catalog_material_documents_document_id'), table_name='catalog_material_documents')
    op.drop_index(op.f('ix_catalog_material_documents_company_id'), table_name='catalog_material_documents')
    op.drop_table('catalog_material_documents')
    op.drop_index(op.f('ix_catalog_materials_status'), table_name='catalog_materials')
    op.drop_index(op.f('ix_catalog_materials_company_id'), table_name='catalog_materials')
    op.drop_index(op.f('ix_catalog_materials_collection_id'), table_name='catalog_materials')
    op.drop_index(op.f('ix_catalog_materials_brand_id'), table_name='catalog_materials')
    op.drop_table('catalog_materials')
    op.drop_index(op.f('ix_catalog_collections_status'), table_name='catalog_collections')
    op.drop_index(op.f('ix_catalog_collections_company_id'), table_name='catalog_collections')
    op.drop_index(op.f('ix_catalog_collections_brand_id'), table_name='catalog_collections')
    op.drop_table('catalog_collections')
    op.drop_index(op.f('ix_catalog_brands_status'), table_name='catalog_brands')
    op.drop_index(op.f('ix_catalog_brands_company_id'), table_name='catalog_brands')
    op.drop_table('catalog_brands')
    op.drop_index(op.f('ix_catalog_warehouses_status'), table_name='catalog_warehouses')
    op.drop_index(op.f('ix_catalog_warehouses_company_id'), table_name='catalog_warehouses')
    op.drop_table('catalog_warehouses')
    op.drop_index(op.f('ix_catalog_price_lists_status'), table_name='catalog_price_lists')
    op.drop_index(op.f('ix_catalog_price_lists_company_id'), table_name='catalog_price_lists')
    op.drop_table('catalog_price_lists')
    # ### end Alembic commands ###
