"""customer portal module tables

Revision ID: 2b84b718b162
Revises: 430944e10164
Create Date: 2026-07-21 17:19:24.503671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '2b84b718b162'
down_revision: Union[str, None] = '430944e10164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_portal_logins',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('customer_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_portal_logins_company_id'), 'customer_portal_logins', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_portal_logins_customer_id'), 'customer_portal_logins', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customer_portal_logins_email'), 'customer_portal_logins', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_portal_logins_email'), table_name='customer_portal_logins')
    op.drop_index(op.f('ix_customer_portal_logins_customer_id'), table_name='customer_portal_logins')
    op.drop_index(op.f('ix_customer_portal_logins_company_id'), table_name='customer_portal_logins')
    op.drop_table('customer_portal_logins')
    # ### end Alembic commands ###
