"""Sprint 5: add completion_status to project items

Revision ID: 4cbc1f1d4028
Revises: fcaddc974e1c
Create Date: 2026-07-09 12:35:22.777782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '4cbc1f1d4028'
down_revision: Union[str, None] = 'fcaddc974e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_project_items', sa.Column('completion_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_project_items', 'completion_status')
    # ### end Alembic commands ###
