"""phase22_payments_and_esignature

Revision ID: 4ce2ed56fa56
Revises: b31a9c8d7e6f
Create Date: 2026-07-24 16:11:02.195451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '4ce2ed56fa56'
down_revision: Union[str, None] = 'b31a9c8d7e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_payment_sessions',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('invoice_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('customer_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_session_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('checkout_url', sa.String(length=1000), nullable=False),
    sa.Column('payment_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['invoice_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_payment_sessions_company_id'), 'invoice_payment_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoice_payment_sessions_customer_id'), 'invoice_payment_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoice_payment_sessions_invoice_id'), 'invoice_payment_sessions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_payment_sessions_provider_session_id'), 'invoice_payment_sessions', ['provider_session_id'], unique=True)
    op.create_index(op.f('ix_invoice_payment_sessions_status'), 'invoice_payment_sessions', ['status'], unique=False)
    op.add_column('installation_jobs', sa.Column('signature_status', sa.String(length=20), nullable=True))
    op.add_column('installation_jobs', sa.Column('signature_provider', sa.String(length=20), nullable=True))
    op.add_column('installation_jobs', sa.Column('signature_provider_request_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_installation_jobs_signature_provider_request_id'), 'installation_jobs', ['signature_provider_request_id'], unique=False)
    op.add_column('sales_project_item_measurements', sa.Column('signature_status', sa.String(length=20), nullable=True))
    op.add_column('sales_project_item_measurements', sa.Column('signature_provider', sa.String(length=20), nullable=True))
    op.add_column('sales_project_item_measurements', sa.Column('signature_provider_request_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_sales_project_item_measurements_signature_provider_request_id'), 'sales_project_item_measurements', ['signature_provider_request_id'], unique=False)
    # ### end Alembic commands ###

    # Phase 18's RLS-continuity convention: a new tenant-owned (company_id)
    # table added after the original RLS migration gets its own policy
    # directly inside its own creation migration (see Phase 19/20/21 for the
    # same pattern). The two column additions above don't need their own
    # policy -- installation_jobs/sales_project_item_measurements are
    # already RLS-enabled tables; new columns on an existing row are still
    # covered by that row's existing policy.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute('ALTER TABLE "invoice_payment_sessions" ENABLE ROW LEVEL SECURITY')
        op.execute(
            'CREATE POLICY company_isolation ON "invoice_payment_sessions" '
            "USING (company_id = current_setting('app.current_company_id', true)::uuid) "
            "WITH CHECK (company_id = current_setting('app.current_company_id', true)::uuid)"
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute('DROP POLICY IF EXISTS company_isolation ON "invoice_payment_sessions"')
        op.execute('ALTER TABLE "invoice_payment_sessions" DISABLE ROW LEVEL SECURITY')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_project_item_measurements_signature_provider_request_id'), table_name='sales_project_item_measurements')
    op.drop_column('sales_project_item_measurements', 'signature_provider_request_id')
    op.drop_column('sales_project_item_measurements', 'signature_provider')
    op.drop_column('sales_project_item_measurements', 'signature_status')
    op.drop_index(op.f('ix_installation_jobs_signature_provider_request_id'), table_name='installation_jobs')
    op.drop_column('installation_jobs', 'signature_provider_request_id')
    op.drop_column('installation_jobs', 'signature_provider')
    op.drop_column('installation_jobs', 'signature_status')
    op.drop_index(op.f('ix_invoice_payment_sessions_status'), table_name='invoice_payment_sessions')
    op.drop_index(op.f('ix_invoice_payment_sessions_provider_session_id'), table_name='invoice_payment_sessions')
    op.drop_index(op.f('ix_invoice_payment_sessions_invoice_id'), table_name='invoice_payment_sessions')
    op.drop_index(op.f('ix_invoice_payment_sessions_customer_id'), table_name='invoice_payment_sessions')
    op.drop_index(op.f('ix_invoice_payment_sessions_company_id'), table_name='invoice_payment_sessions')
    op.drop_table('invoice_payment_sessions')
    # ### end Alembic commands ###
