"""real integrations: channel credentials, message queue, integration logs

Revision ID: 4d0d155e794a
Revises: 65057109c552
Create Date: 2026-07-06 16:33:19.407618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '4d0d155e794a'
down_revision: Union[str, None] = '65057109c552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_channel_credentials',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('channel_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('encrypted_config', sa.Text(), nullable=False),
    sa.Column('webhook_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('imap_last_synced_uid', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['communication_channels.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_channel_credentials_channel_id'), 'communication_channel_credentials', ['channel_id'], unique=True)
    op.create_index(op.f('ix_communication_channel_credentials_company_id'), 'communication_channel_credentials', ['company_id'], unique=False)
    op.create_table('communication_integration_logs',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('channel_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['communication_channels.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_integration_logs_action'), 'communication_integration_logs', ['action'], unique=False)
    op.create_index(op.f('ix_communication_integration_logs_channel_id'), 'communication_integration_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_communication_integration_logs_company_id'), 'communication_integration_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_communication_integration_logs_direction'), 'communication_integration_logs', ['direction'], unique=False)
    op.create_index(op.f('ix_communication_integration_logs_provider'), 'communication_integration_logs', ['provider'], unique=False)
    op.create_table('communication_message_queue',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('message_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('channel_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['communication_channels.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['communication_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_message_queue_channel_id'), 'communication_message_queue', ['channel_id'], unique=False)
    op.create_index(op.f('ix_communication_message_queue_company_id'), 'communication_message_queue', ['company_id'], unique=False)
    op.create_index(op.f('ix_communication_message_queue_message_id'), 'communication_message_queue', ['message_id'], unique=False)
    op.create_index(op.f('ix_communication_message_queue_next_attempt_at'), 'communication_message_queue', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_communication_message_queue_status'), 'communication_message_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_message_queue_status'), table_name='communication_message_queue')
    op.drop_index(op.f('ix_communication_message_queue_next_attempt_at'), table_name='communication_message_queue')
    op.drop_index(op.f('ix_communication_message_queue_message_id'), table_name='communication_message_queue')
    op.drop_index(op.f('ix_communication_message_queue_company_id'), table_name='communication_message_queue')
    op.drop_index(op.f('ix_communication_message_queue_channel_id'), table_name='communication_message_queue')
    op.drop_table('communication_message_queue')
    op.drop_index(op.f('ix_communication_integration_logs_provider'), table_name='communication_integration_logs')
    op.drop_index(op.f('ix_communication_integration_logs_direction'), table_name='communication_integration_logs')
    op.drop_index(op.f('ix_communication_integration_logs_company_id'), table_name='communication_integration_logs')
    op.drop_index(op.f('ix_communication_integration_logs_channel_id'), table_name='communication_integration_logs')
    op.drop_index(op.f('ix_communication_integration_logs_action'), table_name='communication_integration_logs')
    op.drop_table('communication_integration_logs')
    op.drop_index(op.f('ix_communication_channel_credentials_company_id'), table_name='communication_channel_credentials')
    op.drop_index(op.f('ix_communication_channel_credentials_channel_id'), table_name='communication_channel_credentials')
    op.drop_table('communication_channel_credentials')
    # ### end Alembic commands ###
