"""installation module tables

Revision ID: 54f13cedd498
Revises: 69761b0a3f8a
Create Date: 2026-07-04 12:10:04.245269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '54f13cedd498'
down_revision: Union[str, None] = '69761b0a3f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation_crews',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_crews_company_id'), 'installation_crews', ['company_id'], unique=False)
    op.create_index(op.f('ix_installation_crews_status'), 'installation_crews', ['status'], unique=False)
    op.create_table('installation_job_number_sequences',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year', name='uq_installation_job_sequence')
    )
    op.create_index(op.f('ix_installation_job_number_sequences_company_id'), 'installation_job_number_sequences', ['company_id'], unique=False)
    op.create_table('installation_crew_members',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('crew_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('user_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['crew_id'], ['installation_crews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crew_id', 'user_id', name='uq_crew_member')
    )
    op.create_index(op.f('ix_installation_crew_members_company_id'), 'installation_crew_members', ['company_id'], unique=False)
    op.create_index(op.f('ix_installation_crew_members_crew_id'), 'installation_crew_members', ['crew_id'], unique=False)
    op.create_index(op.f('ix_installation_crew_members_user_id'), 'installation_crew_members', ['user_id'], unique=False)
    op.create_table('installation_jobs',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('order_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('job_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('crew_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('scheduled_date', sa.String(length=10), nullable=True),
    sa.Column('scheduled_time_slot', sa.String(length=50), nullable=True),
    sa.Column('route_sequence', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['crew_id'], ['installation_crews.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_jobs_company_id'), 'installation_jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_installation_jobs_crew_id'), 'installation_jobs', ['crew_id'], unique=False)
    op.create_index(op.f('ix_installation_jobs_job_number'), 'installation_jobs', ['job_number'], unique=False)
    op.create_index(op.f('ix_installation_jobs_order_id'), 'installation_jobs', ['order_id'], unique=True)
    op.create_index(op.f('ix_installation_jobs_scheduled_date'), 'installation_jobs', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_installation_jobs_status'), 'installation_jobs', ['status'], unique=False)
    op.create_table('installation_notifications',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('user_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('installation_job_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['installation_job_id'], ['installation_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_notifications_company_id'), 'installation_notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_installation_notifications_installation_job_id'), 'installation_notifications', ['installation_job_id'], unique=False)
    op.create_index(op.f('ix_installation_notifications_user_id'), 'installation_notifications', ['user_id'], unique=False)
    op.create_table('installation_photos',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('installation_job_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('document_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('photo_type', sa.String(length=20), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['installation_job_id'], ['installation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_photos_company_id'), 'installation_photos', ['company_id'], unique=False)
    op.create_index(op.f('ix_installation_photos_document_id'), 'installation_photos', ['document_id'], unique=False)
    op.create_index(op.f('ix_installation_photos_installation_job_id'), 'installation_photos', ['installation_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installation_photos_installation_job_id'), table_name='installation_photos')
    op.drop_index(op.f('ix_installation_photos_document_id'), table_name='installation_photos')
    op.drop_index(op.f('ix_installation_photos_company_id'), table_name='installation_photos')
    op.drop_table('installation_photos')
    op.drop_index(op.f('ix_installation_notifications_user_id'), table_name='installation_notifications')
    op.drop_index(op.f('ix_installation_notifications_installation_job_id'), table_name='installation_notifications')
    op.drop_index(op.f('ix_installation_notifications_company_id'), table_name='installation_notifications')
    op.drop_table('installation_notifications')
    op.drop_index(op.f('ix_installation_jobs_status'), table_name='installation_jobs')
    op.drop_index(op.f('ix_installation_jobs_scheduled_date'), table_name='installation_jobs')
    op.drop_index(op.f('ix_installation_jobs_order_id'), table_name='installation_jobs')
    op.drop_index(op.f('ix_installation_jobs_job_number'), table_name='installation_jobs')
    op.drop_index(op.f('ix_installation_jobs_crew_id'), table_name='installation_jobs')
    op.drop_index(op.f('ix_installation_jobs_company_id'), table_name='installation_jobs')
    op.drop_table('installation_jobs')
    op.drop_index(op.f('ix_installation_crew_members_user_id'), table_name='installation_crew_members')
    op.drop_index(op.f('ix_installation_crew_members_crew_id'), table_name='installation_crew_members')
    op.drop_index(op.f('ix_installation_crew_members_company_id'), table_name='installation_crew_members')
    op.drop_table('installation_crew_members')
    op.drop_index(op.f('ix_installation_job_number_sequences_company_id'), table_name='installation_job_number_sequences')
    op.drop_table('installation_job_number_sequences')
    op.drop_index(op.f('ix_installation_crews_status'), table_name='installation_crews')
    op.drop_index(op.f('ix_installation_crews_company_id'), table_name='installation_crews')
    op.drop_table('installation_crews')
    # ### end Alembic commands ###
