"""ai sales assistant module tables

Revision ID: 65057109c552
Revises: dd6c07691eb7
Create Date: 2026-07-06 14:34:09.036993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '65057109c552'
down_revision: Union[str, None] = 'dd6c07691eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_recommendations',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('analysis_kind', sa.String(length=20), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('edited_response', sa.JSON(), nullable=True),
    sa.Column('requested_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('reviewed_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_analysis_kind'), 'ai_recommendations', ['analysis_kind'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_company_id'), 'ai_recommendations', ['company_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_provider'), 'ai_recommendations', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_recommendation_type'), 'ai_recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_related_entity_id'), 'ai_recommendations', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_related_entity_type'), 'ai_recommendations', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_status'), 'ai_recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_recommendations_status'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_related_entity_type'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_related_entity_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_recommendation_type'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_provider'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_company_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_analysis_kind'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    # ### end Alembic commands ###
