"""stone_fabrication_workflow_phase1

Revision ID: 67e0a8a55a5a
Revises: 2b84b718b162
Create Date: 2026-07-22 10:11:16.584592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '67e0a8a55a5a'
down_revision: Union[str, None] = '2b84b718b162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_stages',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_production_stage_name_per_company')
    )
    op.create_index(op.f('ix_production_stages_company_id'), 'production_stages', ['company_id'], unique=False)
    op.create_table('work_order_events',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('work_order_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('from_value', sa.String(length=200), nullable=True),
    sa.Column('to_value', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_events_company_id'), 'work_order_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_work_order_events_work_order_id'), 'work_order_events', ['work_order_id'], unique=False)
    op.create_table('catalog_slab_reservations',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('slab_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('order_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('order_item_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reserved_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['reserved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['slab_id'], ['catalog_slabs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_slab_reservations_company_id'), 'catalog_slab_reservations', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_slab_reservations_order_id'), 'catalog_slab_reservations', ['order_id'], unique=False)
    op.create_index(op.f('ix_catalog_slab_reservations_order_item_id'), 'catalog_slab_reservations', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_catalog_slab_reservations_slab_id'), 'catalog_slab_reservations', ['slab_id'], unique=False)
    op.create_index(op.f('ix_catalog_slab_reservations_status'), 'catalog_slab_reservations', ['status'], unique=False)
    op.add_column('catalog_slabs', sa.Column('parent_slab_id', core.db.mixins.GUID(), nullable=True))
    op.add_column('catalog_slabs', sa.Column('is_offcut', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_catalog_slabs_parent_slab_id'), 'catalog_slabs', ['parent_slab_id'], unique=False)
    # batch_alter_table: SQLite can't ALTER a table to add a FK constraint
    # (same pattern as fcaddc974e1c_sprint_4_normalize_material_thickness_.py).
    with op.batch_alter_table('catalog_slabs') as batch_op:
        batch_op.create_foreign_key('fk_catalog_slabs_parent_slab_id', 'catalog_slabs', ['parent_slab_id'], ['id'])
    op.add_column('work_orders', sa.Column('priority', sa.String(length=10), server_default='normal', nullable=False))
    op.add_column('work_orders', sa.Column('current_stage_id', core.db.mixins.GUID(), nullable=True))
    op.create_index(op.f('ix_work_orders_current_stage_id'), 'work_orders', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_work_orders_priority'), 'work_orders', ['priority'], unique=False)
    with op.batch_alter_table('work_orders') as batch_op:
        batch_op.create_foreign_key('fk_work_orders_current_stage_id', 'production_stages', ['current_stage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders') as batch_op:
        batch_op.drop_constraint('fk_work_orders_current_stage_id', type_='foreignkey')
    op.drop_index(op.f('ix_work_orders_priority'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_current_stage_id'), table_name='work_orders')
    op.drop_column('work_orders', 'current_stage_id')
    op.drop_column('work_orders', 'priority')
    with op.batch_alter_table('catalog_slabs') as batch_op:
        batch_op.drop_constraint('fk_catalog_slabs_parent_slab_id', type_='foreignkey')
    op.drop_index(op.f('ix_catalog_slabs_parent_slab_id'), table_name='catalog_slabs')
    op.drop_column('catalog_slabs', 'is_offcut')
    op.drop_column('catalog_slabs', 'parent_slab_id')
    op.drop_index(op.f('ix_catalog_slab_reservations_status'), table_name='catalog_slab_reservations')
    op.drop_index(op.f('ix_catalog_slab_reservations_slab_id'), table_name='catalog_slab_reservations')
    op.drop_index(op.f('ix_catalog_slab_reservations_order_item_id'), table_name='catalog_slab_reservations')
    op.drop_index(op.f('ix_catalog_slab_reservations_order_id'), table_name='catalog_slab_reservations')
    op.drop_index(op.f('ix_catalog_slab_reservations_company_id'), table_name='catalog_slab_reservations')
    op.drop_table('catalog_slab_reservations')
    op.drop_index(op.f('ix_work_order_events_work_order_id'), table_name='work_order_events')
    op.drop_index(op.f('ix_work_order_events_company_id'), table_name='work_order_events')
    op.drop_table('work_order_events')
    op.drop_index(op.f('ix_production_stages_company_id'), table_name='production_stages')
    op.drop_table('production_stages')
    # ### end Alembic commands ###
