"""production module tables

Revision ID: 69761b0a3f8a
Revises: fa63389bee5c
Create Date: 2026-07-04 10:59:59.159611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '69761b0a3f8a'
down_revision: Union[str, None] = 'fa63389bee5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_number_sequences',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year', name='uq_work_order_sequence')
    )
    op.create_index(op.f('ix_work_order_number_sequences_company_id'), 'work_order_number_sequences', ['company_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('order_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('work_order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', core.db.mixins.GUID(), nullable=True),
    sa.Column('scheduled_start_date', sa.String(length=10), nullable=True),
    sa.Column('scheduled_completion_date', sa.String(length=10), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_company_id'), 'work_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_work_orders_order_id'), 'work_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_work_order_number'), 'work_orders', ['work_order_number'], unique=False)
    op.create_table('work_order_items',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('work_order_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('order_item_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('slab_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['slab_id'], ['catalog_slabs.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_items_company_id'), 'work_order_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_work_order_items_order_item_id'), 'work_order_items', ['order_item_id'], unique=True)
    op.create_index(op.f('ix_work_order_items_slab_id'), 'work_order_items', ['slab_id'], unique=False)
    op.create_index(op.f('ix_work_order_items_work_order_id'), 'work_order_items', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_items_work_order_id'), table_name='work_order_items')
    op.drop_index(op.f('ix_work_order_items_slab_id'), table_name='work_order_items')
    op.drop_index(op.f('ix_work_order_items_order_item_id'), table_name='work_order_items')
    op.drop_index(op.f('ix_work_order_items_company_id'), table_name='work_order_items')
    op.drop_table('work_order_items')
    op.drop_index(op.f('ix_work_orders_work_order_number'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_order_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_company_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_work_order_number_sequences_company_id'), table_name='work_order_number_sequences')
    op.drop_table('work_order_number_sequences')
    # ### end Alembic commands ###
