"""stone industry customer fields and status

Revision ID: 8c35bb34b2fc
Revises: f59015eb8c1b
Create Date: 2026-06-30 12:01:53.003716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '8c35bb34b2fc'
down_revision: Union[str, None] = 'f59015eb8c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_customers', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('crm_customers', sa.Column('whatsapp', sa.String(), nullable=True))
    op.add_column('crm_customers', sa.Column('instagram', sa.String(), nullable=True))
    op.add_column('crm_customers', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('crm_customers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('crm_customers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('crm_customers', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('crm_customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column(
        'crm_customers',
        sa.Column('status', sa.String(), nullable=False, server_default='new_inquiry'),
    )
    op.create_index(op.f('ix_crm_customers_status'), 'crm_customers', ['status'], unique=False)
    with op.batch_alter_table('crm_customers') as batch_op:
        batch_op.alter_column('status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_customers_status'), table_name='crm_customers')
    op.drop_column('crm_customers', 'status')
    op.drop_column('crm_customers', 'notes')
    op.drop_column('crm_customers', 'company_name')
    op.drop_column('crm_customers', 'address')
    op.drop_column('crm_customers', 'email')
    op.drop_column('crm_customers', 'facebook')
    op.drop_column('crm_customers', 'instagram')
    op.drop_column('crm_customers', 'whatsapp')
    op.drop_column('crm_customers', 'phone')
    # ### end Alembic commands ###
