"""cut_optimization_phase2

Revision ID: 98b251470b25
Revises: 67e0a8a55a5a
Create Date: 2026-07-22 13:19:38.891338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = '98b251470b25'
down_revision: Union[str, None] = '67e0a8a55a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cut_optimization_runs',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('material_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('slab_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('slab_length_mm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('slab_width_mm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kerf_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('pieces', sa.JSON(), nullable=False),
    sa.Column('placements', sa.JSON(), nullable=False),
    sa.Column('unplaced', sa.JSON(), nullable=False),
    sa.Column('total_area_m2', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('placed_area_m2', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('waste_area_m2', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('utilization_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('related_order_item_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('related_quote_item_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['catalog_materials.id'], ),
    sa.ForeignKeyConstraint(['slab_id'], ['catalog_slabs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cut_optimization_runs_company_id'), 'cut_optimization_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_cut_optimization_runs_material_id'), 'cut_optimization_runs', ['material_id'], unique=False)
    op.create_index(op.f('ix_cut_optimization_runs_related_order_item_id'), 'cut_optimization_runs', ['related_order_item_id'], unique=False)
    op.create_index(op.f('ix_cut_optimization_runs_related_quote_item_id'), 'cut_optimization_runs', ['related_quote_item_id'], unique=False)
    op.create_index(op.f('ix_cut_optimization_runs_slab_id'), 'cut_optimization_runs', ['slab_id'], unique=False)
    op.create_index(op.f('ix_cut_optimization_runs_source'), 'cut_optimization_runs', ['source'], unique=False)
    op.add_column('catalog_slabs', sa.Column('image_document_id', core.db.mixins.GUID(), nullable=True))
    # batch_alter_table: SQLite can't ALTER a table to add a FK constraint
    # (same pattern as fcaddc974e1c_sprint_4_normalize_material_thickness_.py
    # and 67e0a8a55a5a_stone_fabrication_workflow_phase1.py).
    with op.batch_alter_table('catalog_slabs') as batch_op:
        batch_op.create_foreign_key('fk_catalog_slabs_image_document_id', 'documents', ['image_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_slabs') as batch_op:
        batch_op.drop_constraint('fk_catalog_slabs_image_document_id', type_='foreignkey')
    op.drop_column('catalog_slabs', 'image_document_id')
    op.drop_index(op.f('ix_cut_optimization_runs_source'), table_name='cut_optimization_runs')
    op.drop_index(op.f('ix_cut_optimization_runs_slab_id'), table_name='cut_optimization_runs')
    op.drop_index(op.f('ix_cut_optimization_runs_related_quote_item_id'), table_name='cut_optimization_runs')
    op.drop_index(op.f('ix_cut_optimization_runs_related_order_item_id'), table_name='cut_optimization_runs')
    op.drop_index(op.f('ix_cut_optimization_runs_material_id'), table_name='cut_optimization_runs')
    op.drop_index(op.f('ix_cut_optimization_runs_company_id'), table_name='cut_optimization_runs')
    op.drop_table('cut_optimization_runs')
    # ### end Alembic commands ###
