"""Sprint 3: Project workspace - rooms, project items, measurements, drawings, photos

Revision ID: ce2e7ce3dca1
Revises: e042f8386f09
Create Date: 2026-07-09 10:24:47.042643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = 'ce2e7ce3dca1'
down_revision: Union[str, None] = 'e042f8386f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_rooms',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('project_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['sales_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_rooms_company_id'), 'sales_rooms', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_rooms_project_id'), 'sales_rooms', ['project_id'], unique=False)
    op.create_table('sales_project_items',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('project_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('room_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('material_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('production_status', sa.String(length=50), nullable=True),
    sa.Column('installation_status', sa.String(length=50), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['catalog_materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['sales_projects.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['sales_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_project_items_company_id'), 'sales_project_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_project_items_material_id'), 'sales_project_items', ['material_id'], unique=False)
    op.create_index(op.f('ix_sales_project_items_project_id'), 'sales_project_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_sales_project_items_room_id'), 'sales_project_items', ['room_id'], unique=False)
    op.create_table('sales_project_item_drawings',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('project_item_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('document_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('drawing_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_item_id'], ['sales_project_items.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_project_item_drawings_company_id'), 'sales_project_item_drawings', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_project_item_drawings_document_id'), 'sales_project_item_drawings', ['document_id'], unique=False)
    op.create_index(op.f('ix_sales_project_item_drawings_project_item_id'), 'sales_project_item_drawings', ['project_item_id'], unique=False)
    op.create_table('sales_project_item_measurements',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('project_item_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('length_mm', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('measurer_name', sa.String(length=200), nullable=False),
    sa.Column('measured_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('customer_signature_document_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_signature_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_item_id'], ['sales_project_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_project_item_measurements_company_id'), 'sales_project_item_measurements', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_project_item_measurements_project_item_id'), 'sales_project_item_measurements', ['project_item_id'], unique=False)
    op.create_table('sales_project_item_photos',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('project_item_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('document_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_item_id'], ['sales_project_items.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_project_item_photos_company_id'), 'sales_project_item_photos', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_project_item_photos_document_id'), 'sales_project_item_photos', ['document_id'], unique=False)
    op.create_index(op.f('ix_sales_project_item_photos_project_item_id'), 'sales_project_item_photos', ['project_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_project_item_photos_project_item_id'), table_name='sales_project_item_photos')
    op.drop_index(op.f('ix_sales_project_item_photos_document_id'), table_name='sales_project_item_photos')
    op.drop_index(op.f('ix_sales_project_item_photos_company_id'), table_name='sales_project_item_photos')
    op.drop_table('sales_project_item_photos')
    op.drop_index(op.f('ix_sales_project_item_measurements_project_item_id'), table_name='sales_project_item_measurements')
    op.drop_index(op.f('ix_sales_project_item_measurements_company_id'), table_name='sales_project_item_measurements')
    op.drop_table('sales_project_item_measurements')
    op.drop_index(op.f('ix_sales_project_item_drawings_project_item_id'), table_name='sales_project_item_drawings')
    op.drop_index(op.f('ix_sales_project_item_drawings_document_id'), table_name='sales_project_item_drawings')
    op.drop_index(op.f('ix_sales_project_item_drawings_company_id'), table_name='sales_project_item_drawings')
    op.drop_table('sales_project_item_drawings')
    op.drop_index(op.f('ix_sales_project_items_room_id'), table_name='sales_project_items')
    op.drop_index(op.f('ix_sales_project_items_project_id'), table_name='sales_project_items')
    op.drop_index(op.f('ix_sales_project_items_material_id'), table_name='sales_project_items')
    op.drop_index(op.f('ix_sales_project_items_company_id'), table_name='sales_project_items')
    op.drop_table('sales_project_items')
    op.drop_index(op.f('ix_sales_rooms_project_id'), table_name='sales_rooms')
    op.drop_index(op.f('ix_sales_rooms_company_id'), table_name='sales_rooms')
    op.drop_table('sales_rooms')
    # ### end Alembic commands ###
