"""crm tasks and task notifications

Revision ID: d5bf0a738a21
Revises: 5df1949c9175
Create Date: 2026-07-06 10:30:19.669483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = 'd5bf0a738a21'
down_revision: Union[str, None] = '5df1949c9175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_tasks',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', core.db.mixins.GUID(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=20), nullable=True),
    sa.Column('recurrence_interval', sa.Integer(), nullable=False),
    sa.Column('recurrence_end_date', sa.String(length=10), nullable=True),
    sa.Column('series_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overdue_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['crm_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_tasks_assigned_to'), 'crm_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_crm_tasks_company_id'), 'crm_tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_due_date'), 'crm_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_crm_tasks_priority'), 'crm_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_crm_tasks_related_entity_id'), 'crm_tasks', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_related_entity_type'), 'crm_tasks', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_crm_tasks_remind_at'), 'crm_tasks', ['remind_at'], unique=False)
    op.create_index(op.f('ix_crm_tasks_series_id'), 'crm_tasks', ['series_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_status'), 'crm_tasks', ['status'], unique=False)
    op.create_table('crm_task_notifications',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('user_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('task_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['crm_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_task_notifications_company_id'), 'crm_task_notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_task_notifications_task_id'), 'crm_task_notifications', ['task_id'], unique=False)
    op.create_index(op.f('ix_crm_task_notifications_user_id'), 'crm_task_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_task_notifications_user_id'), table_name='crm_task_notifications')
    op.drop_index(op.f('ix_crm_task_notifications_task_id'), table_name='crm_task_notifications')
    op.drop_index(op.f('ix_crm_task_notifications_company_id'), table_name='crm_task_notifications')
    op.drop_table('crm_task_notifications')
    op.drop_index(op.f('ix_crm_tasks_status'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_series_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_remind_at'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_related_entity_type'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_related_entity_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_priority'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_due_date'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_company_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_assigned_to'), table_name='crm_tasks')
    op.drop_table('crm_tasks')
    # ### end Alembic commands ###
