"""communication center module tables

Revision ID: dd6c07691eb7
Revises: d5bf0a738a21
Create Date: 2026-07-06 13:05:11.786266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = 'dd6c07691eb7'
down_revision: Union[str, None] = 'd5bf0a738a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_channels',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('identifier', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_channels_channel_type'), 'communication_channels', ['channel_type'], unique=False)
    op.create_index(op.f('ix_communication_channels_company_id'), 'communication_channels', ['company_id'], unique=False)
    op.create_table('communication_message_templates',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=True),
    sa.Column('shortcut', sa.String(length=50), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_message_templates_channel_type'), 'communication_message_templates', ['channel_type'], unique=False)
    op.create_index(op.f('ix_communication_message_templates_company_id'), 'communication_message_templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_communication_message_templates_shortcut'), 'communication_message_templates', ['shortcut'], unique=False)
    op.create_table('communication_conversations',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('channel_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('customer_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('lead_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('project_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('quote_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('order_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('external_contact_id', sa.String(length=200), nullable=False),
    sa.Column('external_contact_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', core.db.mixins.GUID(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.String(length=300), nullable=True),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['communication_channels.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['sales_projects.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_conversations_assigned_to'), 'communication_conversations', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_communication_conversations_channel_id'), 'communication_conversations', ['channel_id'], unique=False)
    op.create_index(op.f('ix_communication_conversations_company_id'), 'communication_conversations', ['company_id'], unique=False)
    op.create_index(op.f('ix_communication_conversations_customer_id'), 'communication_conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_communication_conversations_external_contact_id'), 'communication_conversations', ['external_contact_id'], unique=False)
    op.create_index(op.f('ix_communication_conversations_last_message_at'), 'communication_conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_communication_conversations_lead_id'), 'communication_conversations', ['lead_id'], unique=False)
    op.create_index(op.f('ix_communication_conversations_order_id'), 'communication_conversations', ['order_id'], unique=False)
    op.create_index(op.f('ix_communication_conversations_project_id'), 'communication_conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_communication_conversations_quote_id'), 'communication_conversations', ['quote_id'], unique=False)
    op.create_index(op.f('ix_communication_conversations_status'), 'communication_conversations', ['status'], unique=False)
    op.create_table('communication_conversation_notes',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('conversation_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['communication_conversations.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_conversation_notes_company_id'), 'communication_conversation_notes', ['company_id'], unique=False)
    op.create_index(op.f('ix_communication_conversation_notes_conversation_id'), 'communication_conversation_notes', ['conversation_id'], unique=False)
    op.create_table('communication_messages',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('conversation_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('sender_user_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('template_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('external_message_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['communication_conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['communication_message_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_messages_company_id'), 'communication_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_conversation_id'), 'communication_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_direction'), 'communication_messages', ['direction'], unique=False)
    op.create_table('communication_message_attachments',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('message_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('document_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['communication_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_message_attachments_company_id'), 'communication_message_attachments', ['company_id'], unique=False)
    op.create_index(op.f('ix_communication_message_attachments_document_id'), 'communication_message_attachments', ['document_id'], unique=False)
    op.create_index(op.f('ix_communication_message_attachments_message_id'), 'communication_message_attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_message_attachments_message_id'), table_name='communication_message_attachments')
    op.drop_index(op.f('ix_communication_message_attachments_document_id'), table_name='communication_message_attachments')
    op.drop_index(op.f('ix_communication_message_attachments_company_id'), table_name='communication_message_attachments')
    op.drop_table('communication_message_attachments')
    op.drop_index(op.f('ix_communication_messages_direction'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_conversation_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_company_id'), table_name='communication_messages')
    op.drop_table('communication_messages')
    op.drop_index(op.f('ix_communication_conversation_notes_conversation_id'), table_name='communication_conversation_notes')
    op.drop_index(op.f('ix_communication_conversation_notes_company_id'), table_name='communication_conversation_notes')
    op.drop_table('communication_conversation_notes')
    op.drop_index(op.f('ix_communication_conversations_status'), table_name='communication_conversations')
    op.drop_index(op.f('ix_communication_conversations_quote_id'), table_name='communication_conversations')
    op.drop_index(op.f('ix_communication_conversations_project_id'), table_name='communication_conversations')
    op.drop_index(op.f('ix_communication_conversations_order_id'), table_name='communication_conversations')
    op.drop_index(op.f('ix_communication_conversations_lead_id'), table_name='communication_conversations')
    op.drop_index(op.f('ix_communication_conversations_last_message_at'), table_name='communication_conversations')
    op.drop_index(op.f('ix_communication_conversations_external_contact_id'), table_name='communication_conversations')
    op.drop_index(op.f('ix_communication_conversations_customer_id'), table_name='communication_conversations')
    op.drop_index(op.f('ix_communication_conversations_company_id'), table_name='communication_conversations')
    op.drop_index(op.f('ix_communication_conversations_channel_id'), table_name='communication_conversations')
    op.drop_index(op.f('ix_communication_conversations_assigned_to'), table_name='communication_conversations')
    op.drop_table('communication_conversations')
    op.drop_index(op.f('ix_communication_message_templates_shortcut'), table_name='communication_message_templates')
    op.drop_index(op.f('ix_communication_message_templates_company_id'), table_name='communication_message_templates')
    op.drop_index(op.f('ix_communication_message_templates_channel_type'), table_name='communication_message_templates')
    op.drop_table('communication_message_templates')
    op.drop_index(op.f('ix_communication_channels_company_id'), table_name='communication_channels')
    op.drop_index(op.f('ix_communication_channels_channel_type'), table_name='communication_channels')
    op.drop_table('communication_channels')
    # ### end Alembic commands ###
