"""Add composite indexes on customers and leads (company_id, status/lead_source)

Revision ID: e042f8386f09
Revises: 4d0d155e794a
Create Date: 2026-07-07 14:48:54.814965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = 'e042f8386f09'
down_revision: Union[str, None] = '4d0d155e794a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_crm_customers_company_lead_source', 'crm_customers', ['company_id', 'lead_source'], unique=False)
    op.create_index('ix_crm_customers_company_status', 'crm_customers', ['company_id', 'status'], unique=False)
    op.create_index('ix_crm_leads_company_source_channel', 'crm_leads', ['company_id', 'source_channel'], unique=False)
    op.create_index('ix_crm_leads_company_status', 'crm_leads', ['company_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crm_leads_company_status', table_name='crm_leads')
    op.drop_index('ix_crm_leads_company_source_channel', table_name='crm_leads')
    op.drop_index('ix_crm_customers_company_status', table_name='crm_customers')
    op.drop_index('ix_crm_customers_company_lead_source', table_name='crm_customers')
    # ### end Alembic commands ###
