"""sales_module_tables

Revision ID: e623ed6f15b5
Revises: 04ccadfeecf3
Create Date: 2026-07-01 10:24:24.995141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = 'e623ed6f15b5'
down_revision: Union[str, None] = '04ccadfeecf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_service_prices',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('service_key', sa.String(length=100), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'service_key', name='uq_company_service_price')
    )
    op.create_index(op.f('ix_company_service_prices_company_id'), 'company_service_prices', ['company_id'], unique=False)
    op.create_table('sales_projects',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('customer_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', core.db.mixins.GUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_projects_assigned_to'), 'sales_projects', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_sales_projects_company_id'), 'sales_projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_projects_customer_id'), 'sales_projects', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_projects_status'), 'sales_projects', ['status'], unique=False)
    op.create_table('sales_quote_number_sequences',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year', name='uq_quote_sequence')
    )
    op.create_index(op.f('ix_sales_quote_number_sequences_company_id'), 'sales_quote_number_sequences', ['company_id'], unique=False)
    op.create_table('sales_quotes',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('project_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('customer_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_list_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('valid_until', sa.String(length=10), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('prepared_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal_gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal_after_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_final', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_internal_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit_margin_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['catalog_price_lists.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['sales_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_quotes_company_id'), 'sales_quotes', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_quotes_customer_id'), 'sales_quotes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_quotes_project_id'), 'sales_quotes', ['project_id'], unique=False)
    op.create_index(op.f('ix_sales_quotes_quote_number'), 'sales_quotes', ['quote_number'], unique=False)
    op.create_index(op.f('ix_sales_quotes_status'), 'sales_quotes', ['status'], unique=False)
    op.create_table('sales_quote_sections',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('quote_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_measured_area', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('subtotal_sale', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_quote_sections_company_id'), 'sales_quote_sections', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_quote_sections_quote_id'), 'sales_quote_sections', ['quote_id'], unique=False)
    op.create_table('sales_quote_section_measurements',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('section_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('quote_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('length_mm', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('waste_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('required_area_m2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('override_required_area', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sales_quote_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_quote_section_measurements_company_id'), 'sales_quote_section_measurements', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_quote_section_measurements_quote_id'), 'sales_quote_section_measurements', ['quote_id'], unique=False)
    op.create_index(op.f('ix_sales_quote_section_measurements_section_id'), 'sales_quote_section_measurements', ['section_id'], unique=False)
    op.create_table('sales_quote_section_items',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('section_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('quote_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('material_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('slab_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('unit_sale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total_sale', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['catalog_materials.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sales_quote_sections.id'], ),
    sa.ForeignKeyConstraint(['slab_id'], ['catalog_slabs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_quote_section_items_company_id'), 'sales_quote_section_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_quote_section_items_material_id'), 'sales_quote_section_items', ['material_id'], unique=False)
    op.create_index(op.f('ix_sales_quote_section_items_quote_id'), 'sales_quote_section_items', ['quote_id'], unique=False)
    op.create_index(op.f('ix_sales_quote_section_items_section_id'), 'sales_quote_section_items', ['section_id'], unique=False)
    op.create_index(op.f('ix_sales_quote_section_items_slab_id'), 'sales_quote_section_items', ['slab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_quote_section_items_slab_id'), table_name='sales_quote_section_items')
    op.drop_index(op.f('ix_sales_quote_section_items_section_id'), table_name='sales_quote_section_items')
    op.drop_index(op.f('ix_sales_quote_section_items_quote_id'), table_name='sales_quote_section_items')
    op.drop_index(op.f('ix_sales_quote_section_items_material_id'), table_name='sales_quote_section_items')
    op.drop_index(op.f('ix_sales_quote_section_items_company_id'), table_name='sales_quote_section_items')
    op.drop_table('sales_quote_section_items')
    op.drop_index(op.f('ix_sales_quote_section_measurements_section_id'), table_name='sales_quote_section_measurements')
    op.drop_index(op.f('ix_sales_quote_section_measurements_quote_id'), table_name='sales_quote_section_measurements')
    op.drop_index(op.f('ix_sales_quote_section_measurements_company_id'), table_name='sales_quote_section_measurements')
    op.drop_table('sales_quote_section_measurements')
    op.drop_index(op.f('ix_sales_quote_sections_quote_id'), table_name='sales_quote_sections')
    op.drop_index(op.f('ix_sales_quote_sections_company_id'), table_name='sales_quote_sections')
    op.drop_table('sales_quote_sections')
    op.drop_index(op.f('ix_sales_quotes_status'), table_name='sales_quotes')
    op.drop_index(op.f('ix_sales_quotes_quote_number'), table_name='sales_quotes')
    op.drop_index(op.f('ix_sales_quotes_project_id'), table_name='sales_quotes')
    op.drop_index(op.f('ix_sales_quotes_customer_id'), table_name='sales_quotes')
    op.drop_index(op.f('ix_sales_quotes_company_id'), table_name='sales_quotes')
    op.drop_table('sales_quotes')
    op.drop_index(op.f('ix_sales_quote_number_sequences_company_id'), table_name='sales_quote_number_sequences')
    op.drop_table('sales_quote_number_sequences')
    op.drop_index(op.f('ix_sales_projects_status'), table_name='sales_projects')
    op.drop_index(op.f('ix_sales_projects_customer_id'), table_name='sales_projects')
    op.drop_index(op.f('ix_sales_projects_company_id'), table_name='sales_projects')
    op.drop_index(op.f('ix_sales_projects_assigned_to'), table_name='sales_projects')
    op.drop_table('sales_projects')
    op.drop_index(op.f('ix_company_service_prices_company_id'), table_name='company_service_prices')
    op.drop_table('company_service_prices')
    # ### end Alembic commands ###
