"""crm module tables

Revision ID: f59015eb8c1b
Revises: a03f9e56a601
Create Date: 2026-06-30 09:32:11.561783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = 'f59015eb8c1b'
down_revision: Union[str, None] = 'a03f9e56a601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, manually adjusted to break the
    # crm_customers <-> crm_contacts circular FK: crm_customers is created
    # first WITHOUT primary_contact_id's FK constraint, crm_contacts is
    # created referencing it, then the FK on crm_customers is added via
    # batch_alter_table (Postgres-safe; SQLite uses table-rebuild under the
    # hood via batch mode). ###
    op.create_table('crm_customers',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('primary_contact_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('assigned_manager_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('lead_source', sa.String(), nullable=True),
    sa.Column('advertising_campaign', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_customers_company_id'), 'crm_customers', ['company_id'], unique=False)
    op.create_table('crm_contacts',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('customer_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_contacts_company_id'), 'crm_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_customer_id'), 'crm_contacts', ['customer_id'], unique=False)
    with op.batch_alter_table('crm_customers') as batch_op:
        batch_op.create_foreign_key(
            'fk_crm_customers_primary_contact_id', 'crm_contacts', ['primary_contact_id'], ['id']
        )
    op.create_table('crm_activities',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(), nullable=False),
    sa.Column('related_entity_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_activities_company_id'), 'crm_activities', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_related_entity_id'), 'crm_activities', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_related_entity_type'), 'crm_activities', ['related_entity_type'], unique=False)
    op.create_table('crm_leads',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('source_channel', sa.String(), nullable=False),
    sa.Column('campaign', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_manager_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('converted_customer_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('converted_contact_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['converted_contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['converted_customer_id'], ['crm_customers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_leads_company_id'), 'crm_leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_source_channel'), 'crm_leads', ['source_channel'], unique=False)
    op.create_index(op.f('ix_crm_leads_status'), 'crm_leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_leads_status'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_source_channel'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_company_id'), table_name='crm_leads')
    op.drop_table('crm_leads')
    op.drop_index(op.f('ix_crm_activities_related_entity_type'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_related_entity_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_company_id'), table_name='crm_activities')
    op.drop_table('crm_activities')
    with op.batch_alter_table('crm_customers') as batch_op:
        batch_op.drop_constraint('fk_crm_customers_primary_contact_id', type_='foreignkey')
    op.drop_index(op.f('ix_crm_contacts_customer_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_company_id'), table_name='crm_contacts')
    op.drop_table('crm_contacts')
    op.drop_index(op.f('ix_crm_customers_company_id'), table_name='crm_customers')
    op.drop_table('crm_customers')
    # ### end Alembic commands ###
