"""orders module tables

Revision ID: fa63389bee5c
Revises: e623ed6f15b5
Create Date: 2026-07-04 10:17:45.137905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = 'fa63389bee5c'
down_revision: Union[str, None] = 'e623ed6f15b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_number_sequences',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year', name='uq_order_sequence')
    )
    op.create_index(op.f('ix_order_number_sequences_company_id'), 'order_number_sequences', ['company_id'], unique=False)
    op.create_table('orders',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('project_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('customer_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('quote_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('production_notes', sa.Text(), nullable=True),
    sa.Column('installation_notes', sa.Text(), nullable=True),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('scheduled_production_date', sa.String(length=10), nullable=True),
    sa.Column('scheduled_installation_date', sa.String(length=10), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('created_by', core.db.mixins.GUID(), nullable=True),
    sa.Column('subtotal_gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal_after_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_final', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_internal_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['sales_projects.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_company_id'), 'orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_index(op.f('ix_orders_project_id'), 'orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_orders_quote_id'), 'orders', ['quote_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('order_sections',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('order_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_measured_area', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('subtotal_sale', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_sections_company_id'), 'order_sections', ['company_id'], unique=False)
    op.create_index(op.f('ix_order_sections_order_id'), 'order_sections', ['order_id'], unique=False)
    op.create_table('order_measurements',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('order_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('section_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('length_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('required_area_m2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('waste_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('override_required_area', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['order_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_measurements_company_id'), 'order_measurements', ['company_id'], unique=False)
    op.create_index(op.f('ix_order_measurements_order_id'), 'order_measurements', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_measurements_section_id'), 'order_measurements', ['section_id'], unique=False)
    op.create_table('order_items',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('order_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('section_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('material_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('slab_id', core.db.mixins.GUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('unit_sale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total_sale', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('production_status', sa.String(length=50), nullable=True),
    sa.Column('installation_status', sa.String(length=50), nullable=True),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['catalog_materials.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['order_sections.id'], ),
    sa.ForeignKeyConstraint(['slab_id'], ['catalog_slabs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_company_id'), 'order_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_order_items_material_id'), 'order_items', ['material_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_section_id'), 'order_items', ['section_id'], unique=False)
    op.create_index(op.f('ix_order_items_slab_id'), 'order_items', ['slab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_slab_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_section_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_material_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_company_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_measurements_section_id'), table_name='order_measurements')
    op.drop_index(op.f('ix_order_measurements_order_id'), table_name='order_measurements')
    op.drop_index(op.f('ix_order_measurements_company_id'), table_name='order_measurements')
    op.drop_table('order_measurements')
    op.drop_index(op.f('ix_order_sections_order_id'), table_name='order_sections')
    op.drop_index(op.f('ix_order_sections_company_id'), table_name='order_sections')
    op.drop_table('order_sections')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_quote_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_project_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_company_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_number_sequences_company_id'), table_name='order_number_sequences')
    op.drop_table('order_number_sequences')
    # ### end Alembic commands ###
