"""Sprint 4: normalize Material thickness/size options, extend project items

Revision ID: fcaddc974e1c
Revises: ce2e7ce3dca1
Create Date: 2026-07-09 11:47:06.612218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.mixins


revision: str = 'fcaddc974e1c'
down_revision: Union[str, None] = 'ce2e7ce3dca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_material_sizes',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('material_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('dimensions', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['catalog_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_material_sizes_company_id'), 'catalog_material_sizes', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_material_sizes_material_id'), 'catalog_material_sizes', ['material_id'], unique=False)
    op.create_table('catalog_material_thicknesses',
    sa.Column('company_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('material_id', core.db.mixins.GUID(), nullable=False),
    sa.Column('thickness_mm', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', core.db.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['catalog_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_material_thicknesses_company_id'), 'catalog_material_thicknesses', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_material_thicknesses_material_id'), 'catalog_material_thicknesses', ['material_id'], unique=False)
    # batch_alter_table: SQLite can't ALTER a table to add a FK constraint
    # directly (no ALTER TABLE ADD CONSTRAINT support), so the add-column +
    # add-FK pair is done via the copy-and-move batch strategy, which also
    # works unchanged against Postgres in production.
    with op.batch_alter_table('sales_project_items') as batch_op:
        batch_op.add_column(sa.Column('material_thickness_id', core.db.mixins.GUID(), nullable=True))
        batch_op.add_column(sa.Column('material_size_id', core.db.mixins.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_project_items_material_size_id'), ['material_size_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_project_items_material_thickness_id'), ['material_thickness_id'], unique=False)
        batch_op.create_foreign_key('fk_sales_project_items_material_size_id', 'catalog_material_sizes', ['material_size_id'], ['id'])
        batch_op.create_foreign_key('fk_sales_project_items_material_thickness_id', 'catalog_material_thicknesses', ['material_thickness_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_project_items') as batch_op:
        batch_op.drop_constraint('fk_sales_project_items_material_thickness_id', type_='foreignkey')
        batch_op.drop_constraint('fk_sales_project_items_material_size_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_project_items_material_thickness_id'))
        batch_op.drop_index(batch_op.f('ix_sales_project_items_material_size_id'))
        batch_op.drop_column('material_size_id')
        batch_op.drop_column('material_thickness_id')
    op.drop_index(op.f('ix_catalog_material_thicknesses_material_id'), table_name='catalog_material_thicknesses')
    op.drop_index(op.f('ix_catalog_material_thicknesses_company_id'), table_name='catalog_material_thicknesses')
    op.drop_table('catalog_material_thicknesses')
    op.drop_index(op.f('ix_catalog_material_sizes_material_id'), table_name='catalog_material_sizes')
    op.drop_index(op.f('ix_catalog_material_sizes_company_id'), table_name='catalog_material_sizes')
    op.drop_table('catalog_material_sizes')
    # ### end Alembic commands ###
